export const districts = {
    'An Giang': ['Châu Đốc', 'Long Xuyên', 'Tân Châu', 'An Phú', 'Châu Phú', 'Châu Thành', 'Chợ Mới', 'Phú Tân', 'Thoại Sơn', 'Tịnh Biên', 'Tri Tôn'],
    'Bà Rịa - Vũng Tàu': ['Bà Rịa', 'Vũng Tàu', 'Phú Mỹ', 'Châu Đức', 'Côn Đảo', 'Đất Đỏ', 'Long Điền', 'Xuyên Mộc'],
    'Bắc Giang': ['Bắc Giang', 'Hiệp Hoà', 'Lạng Giang', 'Lục Nam', 'Lục Ngạn', 'Sơn Động', 'Tân Yên', 'Việt Yên', 'Yên Dũng', 'Yên Thế'],
    'Bắc Kạn': ['Bắc Kạn', 'Ba Bể', 'Bạch Thông', 'Chợ Đồn', 'Chợ Mới', 'Na Rì', 'Ngân Sơn', 'Pác Nặm'],
    'Bạc Liêu': ['Bạc Liêu', 'Giá Rai', 'Đông Hải', 'Hòa Bình', 'Hồng Dân', 'Phước Long', 'Vĩnh Lợi'],
    'Bắc Ninh': ['Bắc Ninh', 'Từ Sơn', 'Gia Bình', 'Lương Tài', 'Quế Võ', 'Thuận Thành', 'Tiên Du', 'Yên Phong'],
    'Bến Tre': ['Bến Tre', 'Ba Tri', 'Bình Đại', 'Châu Thành', 'Chợ Lách', 'Giồng Trôm', 'Mỏ Cày Bắc', ' Mỏ Cày Nam', 'Thạnh Phú'],
    'Bình Định': ['Quy Nhơn', 'An Nhơn', 'An Lão', 'Hoài Nhơn', 'Hoài Ân', 'Phù Mỹ', 'Vĩnh Thạnh', ' Tây Sơn', 'Phù Cát', 'Tuy Phước', 'Vân Canh'],
    'Bình Dương': ['Dĩ An', 'Thủ Dầu Một', 'Thuận An', 'Bến Cát', 'Tân Uyên', 'Bắc Tân Uyên', 'Bàu Bàng', ' Dầu Tiếng', 'Phú Giáo'],
    'Bình Phước': ['Đồng Xoài', 'Phước Long', 'Bình Long', 'Chơn Thành', 'Đồng Phú', 'Bù Đăng', 'Bù Đốp', 'Bù Gia Mập', 'Lộc Ninh', 'Hớn Quản', 'Phú Riềng'],
    'Bình Thuận': ['Phan Thiết', 'La Gi', 'Bắc Bình', 'Đức Linh', 'Hàm Tân', 'Hàm Thuận Bắc', 'Hàm Thuận Nam', 'Phú Quý', 'Tánh Linh', 'Tuy Phong'],
    'Cà Mau': ['Cà Mau', 'Thới Bình', 'U Minh', 'Trần Văn Thời', 'Cái Nước', 'Đầm Dơi', 'Ngọc Hiển', 'Năm Căn', 'Phú Tân'],
    'Cần Thơ': ['Ninh Kiều', 'Bình Thủy', 'Cái Răng', 'Ô Môn', 'Thốt Nốt', 'Vĩnh Thạnh', 'Phong Điền', 'Thới Lai', 'Cờ Đỏ'],
    'Cao Bằng': ['Cao Bằng', 'Trùng Khánh', 'Hà Quảng', 'Bảo Lạc', 'Bảo Lâm', 'Hạ Lang', 'Hòa An', 'Nguyên Bình', 'Quảng Hòa', 'Thạch An'],
    'Đà Nẵng': ['Cẩm Lệ', 'Hải Châu', 'Liên Chiểu', 'Ngũ Hành Sơn', 'Sơn Trà', 'Thanh Khê', 'Hòa Vang', 'Hoàng Sa'],
    'Đắk Lắk': ['Buôn Ma Thuột', 'Buôn Hồ', 'Buôn Đôn', 'Cư Kuin', 'Cư M’gar', 'Ea H’leo', 'Ea Kar', 'Ea Súp', 'Krông Ana', 'Krông Bông', 'Krông Búk', 'Krông Năng', 'Krông Pắk', 'Lắk', 'M’Đrắk'],
    'Đắk Nông': ['Gia Nghĩa', 'Cư Jút', 'Đắk Glong', 'Đắk Mil', 'Đắk R’lấp', 'Đắk Song', 'Krông Nô', 'Tuy Đức'],
    'Điện Biên': ['Điện Biên Phủ', 'Mường Nhé', 'Mường Lay', 'Tủa Chùa', 'Tuần Giáo', 'Mường Chà', 'Mường Ảng', 'Điện Biên', 'Điện Biên Đông', 'Nậm Pồ'],
    'Đồng Nai': ['Biên Hoà', 'Vĩnh Cửu', 'Tân Phú', 'Định Quán', 'Thống Nhất', 'Long Khánh', 'Xuân Lộc', 'Long Thành', 'Nhơn Trạch', 'Trảng Bom', 'Cẩm Mỹ'],
    'Đồng Tháp': ['Cao Lãnh', 'Sa Đéc', 'Hồng Ngự', 'Cao Lãnh', 'Châu Thành', 'Hồng Ngự', 'Lai Vung', 'Lấp Vò', 'Tam Nông', 'Tân Hồng', 'Thanh Bình', 'Tháp Mười'],
    'Gia Lai': ['Pleiku', 'Chư Păh', 'Mang Yang', 'Kbang', 'An Khê', 'Kông Chro', 'Đức Cơ', 'Chưprông', 'Chư Sê', 'Ayunpa', 'Krông Pa', 'Ia Grai', 'Đăk Đoa', 'Ia Pa', 'Đăk Pơ', 'Phú Thiện'],
    'Hà Giang': ['Hà Giang', 'Đồng Văn', 'Mèo Vạc', 'Yên Minh', 'Quản Bạ', 'Vị Xuyên', 'Bắc Mê', 'Hoàng Su Phì', 'Xín Mần', 'Bắc Quang', 'Quang Bình'],
    'Hà Nam': ['Phủ Lý', 'Duy Tiên', 'Kim Bảng', 'Lý Nhân', 'Thanh Liêm', 'Bình Lục'],
    'Hà Nội': ['Ba Đình', 'Bắc Từ Liêm', 'Cầu Giấy', 'Đống Đa', 'Hà Đông', 'Hai Bà Trưng', 'Hoàn Kiếm', 'Hoàng Mai', 'Long Biên', 'Nam Từ Liêm', 'Tây Hồ', 'Thanh Xuân', 'Sơn Tây', 'Ba Vì', 'Chương Mỹ', 'Đan Phượng','Đông Anh', 'Gia Lâm', 'Hoài Đức', 'Mê Linh', 'Mỹ Đức', 'Phú Xuyên', 'Phúc Thọ', 'Quốc Oai', 'Sóc Sơn', 'Thạch Thất', 'Thanh Oai', 'Thanh Trì', 'Thường Tín', 'Ứng Hoà'],
    'Hà Tĩnh': ['Hà Tĩnh', 'Hồng Lĩnh', 'Hương Sơn', 'Đức Thọ', 'Nghi Xuân', 'Can Lộc', 'Hương Khê', 'Thạch Hà', 'Cẩm Xuyên', 'Kỳ Anh', 'Vũ Quang', 'Lộc Hà'],
    'Hải Dương': ['Hải Dương', 'Chí Linh', 'Nam Sách', 'Kinh Môn', 'Gia Lộc', 'Tứ Kỳ', 'Thanh Miện', 'Ninh Giang', 'Cẩm Giàng', 'Thanh Hà', 'Kim Thành', 'Bình Giang'],
    'Hải Phòng': ['Đồ Sơn', 'Dương Kinh', 'Hải An', 'Hồng Bàng', 'Kiến An', 'Lê Chân', 'Ngô Quyền', 'An Dương', 'An Lão', 'Bạch Long Vĩ', 'Cát Hải', 'Kiến Thuỵ', 'Quế Võ', 'Thủy Nguyên', 'Tiên Lãng', 'Vĩnh Bảo'],
    'Hậu Giang': ['Vị Thanh', 'Ngã Bảy', 'Vị Thủy', 'Phụng Hiệp', 'Châu Thành', 'Châu Thành A', 'Long Mỹ', 'Long Mỹ (thị xã)'],
    'Hòa Bình': ['Hoà Bình', 'Cao Phong', 'Đà Bắc', 'Kim Bôi', 'Lạc Sơn', 'Lạc Thủy', 'Lương Sơn', 'Mai Châu', 'Tân Lạc', 'Yên Thủy'],
    'Hưng Yên': ['Hưng Yên', 'Mỹ Hào', 'Ân Thi', 'Khoái Châu', 'Kim Động', 'Phù Cừ', 'Tiên Lữ', 'Văn Giang', 'Văn Lâm', 'Yên Mỹ'],
    'Khánh Hòa': ['Cam Ranh', 'Nha Trang', 'Ninh Hòa', 'Cam Lâm', 'Trường Sa', 'Diên Khánh', 'Khánh Sơn', 'Khánh Vĩnh', 'Vạn Ninh'],
    'Kiên Giang': ['Rạch Giá', 'Hà Tiên', 'An Biên', 'An Minh', 'Châu Thành', 'Giang Thành', 'Giồng Riềng', 'Gò Quao', 'Hòn Đất', 'Kiên Hải', 'Kiên Lương', 'Phú Quốc', 'Tân Hiệp', 'U Minh Thượng', 'Vĩnh Thuận'],
    'Kon Tum': ['Kon Tum', 'Đăk Hà', 'Đăk Tô', 'Ngọc Hồi', 'Đăk Glei', 'Sa Thầy', 'Tu Mơ Rông', 'Kon Rẫy', 'Kon Plông', "Ia H'Drai"],
    'Lai Châu': ['Lai Châu', 'Tam Đường', 'Phong Thổ', 'Sìn Hồ', 'Mường Tè', 'Than Uyên'],
    'Lâm Đồng': ['Bảo Lộc', 'Đà Lạt', 'Bảo Lâm', 'Cát Tiên', 'Di Linh', 'Đạ Huoai', 'Đạ Tẻh', 'Đam Rông', 'Đơn Dương', 'Đức Trọng', 'Lạc Dương', 'Lâm Hà'],
    'Lạng Sơn': ['Lạng Sơn', 'Tràng Định', 'Bình Gia', 'Văn Lãng', 'Bắc Sơn', 'Văn Quan', 'Cao Lộc', 'Lộc Bình', 'Chi Lăng', 'Đình Lập', 'Hữu Lũng'],
    'Lào Cai': ['Lào Cai', 'Sa Pa', 'Bắc Hà', 'Bảo Thắng', 'Bảo Yên', 'Bát Xát', 'Mường Khương', 'Si Ma Cai', 'Văn Bàn'],
    'Long An': ['Tân An', 'Vĩnh Hưng', 'Mộc Hoá', 'Tân Thạnh', 'Thạnh Hoá', 'Đức Huệ', 'Đức Hoà', 'Bến Lức', 'Thủ Thừa', 'Châu Thành', 'Tân Trụ', 'Cần Đước', 'Cần Giuộc', 'Tân Hưng'],
    'Nam Định': ['Nam Định', 'Giao Thủy', 'Hải Hậu', 'Mỹ Lộc', 'Nam Trực', 'Nghĩa Hưng', 'Trực Ninh', 'Vụ Bản', 'Xuân Trường', 'Ý Yên'],
    'Nghệ An': ['Vinh', 'Cửa Lò', 'Hoàng Mai', 'Thái Hòa', 'Anh Sơn', 'Con Cuông', 'Diễn Châu', 'Đô Lương', 'Hưng Nguyên', 'Kỳ Sơn', 'Nam Đàn', 'Nghi Lộc', 'Nghĩa Đàn', 'Quế Phong', 'Quỳ Châu', 'Quỳ Hợp', 'Quỳnh Lưu', 'Tân Kỳ', 'Thanh Chương', 'Tương Dương', 'Yên Thành'],
    'Ninh Bình': ['Ninh Bình', 'Tam Điệp', 'Nho Quan', 'Gia Viễn', 'Hoa Lư', 'Yên Mô', 'Kim Sơn', 'Yên Khánh'],
    'Ninh Thuận': ['Phan Rang - Tháp Chàm', 'Bác Ái', 'Ninh Hải', 'Ninh Phước', 'Ninh Sơn', 'Thuận Bắc', 'Thuận Nam'],
    'Phú Thọ': ['Việt Trì', 'Phú Thọ', 'Đoan Hùng', 'Thanh Ba', 'Hạ Hoà', 'Cẩm Khê', 'Yên Lập', 'Thanh Sơn', 'Phù Ninh', 'Lâm Thao', 'Tam Nông', 'Thanh Thủy', 'Tân Sơn'],
    'Phú Yên': ['Tuy Hoà', 'Đồng Xuân', 'Sông Cầu', 'Tuy An', 'Sơn Hoà', 'Sông Hinh', 'Đông Hoà', 'Phú Hoà', 'Tây Hoà'],
    'Quảng Bình': ['Đồng Hới', 'Ba Đồn', 'Lệ Thủy', 'Quảng Ninh', 'Bố Trạch', 'Quảng Trạch', 'Tuyên Hóa', 'Minh Hóa'],
    'Quảng Nam': ['Hội An', 'Tam Kỳ', 'Điện Bàn', 'Bắc Trà My', 'Đại Lộc', 'Đông Giang', 'Duy Xuyên', 'Hiệp Đức', 'Nam Giang', 'Nam Trà My', 'Nông Sơn', 'Núi Thành', 'Phú Ninh', 'Phước Sơn', 'Quế Sơn', 'Tây Giang', 'Thăng Bình', 'Tiên Phước'],
    'Quảng Ngãi': ['Quảng Ngãi', 'Lý Sơn', 'Bình Sơn', 'Trà Bồng', 'Sơn Tịnh', 'Sơn Hà', 'Tư Nghĩa', 'Nghĩa Hành', 'Minh Long', 'Mộ Đức', 'Đức Phổ', 'Ba Tơ', 'Sơn Tây', 'Tây Trà'],
    'Quảng Ninh': ['Hạ Long', 'Cẩm Phả', 'Uông Bí', 'Móng Cái', 'Bình Liêu', 'Đầm Hà', 'Hải Hà', 'Tiên Yên', 'Ba Chẽ', 'Đông Triều', 'Yên Hưng', 'Hoành Bồ', 'Vân Đồn', 'Cô Tô'],
    'Quảng Trị': ['Đông Hà', 'Quảng Trị', 'Vĩnh Linh', 'Gio Linh', 'Cam Lộ', 'Triệu Phong', 'Hải Lăng', 'Hướng Hoá', 'Đăk Rông', 'đảo Cồn cỏ'],
    'Sóc Trăng': ['Sóc Trăng', 'Kế Sách', 'Mỹ Tú', 'Mỹ Xuyên', 'Thạnh Trị', 'Long Phú', 'Vĩnh Châu', 'Cù Lao Dung', 'Ngã Năm', 'Châu Thành', 'Trần Đề'],
    'Sơn La': ['Sơn La', 'Quỳnh Nhai', 'Mường La', 'Thuận Châu', 'Bắc Yên', 'Phù Yên', 'Mai Sơn', 'Yên Châu', 'Sông Mã', 'Mộc Châu', 'Sốp Cộp'],
    'Tây Ninh': ['Tây Ninh', 'Tân Biên', 'Tân Châu', 'Dương Minh Châu', 'Châu Thành', 'Hoà Thành', 'Bến Cầu', 'Gò Dầu', 'Trảng Bàng'],
    'Thái Bình': ['Đông Hưng', 'Hưng Hà', 'Kiến Xương', 'Thái Bình', 'Thái Thụy', 'Tiền Hải', 'Vũ Thư', 'Quỳnh Phụ'],
    'Thái Nguyên': ['Thái Nguyên', 'Sông Công', 'Định Hoá', 'Phú Lương', 'Võ Nhai', 'Đại Từ', 'Đồng Hỷ', 'Phú Bình', 'Phổ Yên'],
    'Thanh Hóa': ['Thanh Hóa', 'Bỉm Sơn', 'Sầm Sơn', 'Đông Sơn', 'Quảng Xương', 'Hoằng Hóa', 'Hậu Lộc', 'Hà Trung', 'Nga Sơn', 'Thiệu Hóa', 'Triệu Sơn', 'Yên Định', 'Tĩnh Gia', 'Nông Cống', 'Ngọc Lặc', 'Cẩm Thủy', 'Thạch Thành', 'Vĩnh Lộc', 'Thọ Xuân', 'Như Thanh', 'Như Xuân', 'Thường Xuân', 'Lang Chánh', 'Bá Thước', 'Quan Hóa', 'Quan Sơn', 'Mường Lát'],
    'Thừa Thiên Huế': ['Huế', 'A lưới', ' Hương Thủy', 'Hương Trà', 'Nam Đông', 'Phong Điền', 'Phú Lộc', 'Phú Vang', 'Quảng Điền'],
    'Tiền Giang': ['Mỹ Tho', 'Gò Công', 'Cai Lậy (thị xã)', 'Cai Lậy', 'Cái Bè', 'Tân Phước', 'Châu Thành', 'Chợ Gạo', 'Gò Công Tây', 'Gò Công Đông', 'Tân Phú Đông'],
    'Thành phố Hồ Chí Minh': ['Quận 1', 'Quận 2', 'Quận 3', 'Quận 4', 'Quận 5', 'Quận 6', 'Quận 7', 'Quận 8', 'Quận 9', 'Quận 10', 'Quận 11', 'Quận 12', 'Bình Tân', 'Bình Thạnh', 'Gò Vấp', 'Phú Nhuận', 'Tân Bình', 'Tân Phú', 'Thủ Đức', 'Bình Chánh', 'Cần Giờ', 'Củ Chi', 'Hóc Môn', 'Nhà Bè'],
    'Trà Vinh': ['Trà Vinh', 'Duyên Hải', 'Càng Long', 'Cầu Kè', 'Cầu Ngang', 'Châu Thành', 'Duyên Hải (thị xã)', 'Tiểu Cần', 'Trà Cú'],
    'Tuyên Quang': ['Tuyên Quang','Sơn Dương', 'Yên Sơn', 'Hàm Yên', 'Chiêm Hóa', 'Na Hang', 'Lâm Bình'],
    'Vĩnh Long': ['Vĩnh Long', 'Bình Minh', 'Bình Tân', 'Long Hồ', 'Mang Thít', 'Tam Bình', 'Trà Ôn', 'Vũng Liêm'],
    'Vĩnh Phúc': ['Phúc Yên', 'Vĩnh Yên', 'Bình Xuyên', 'Lập Thạch', 'Sông Lô', 'Tam Đảo', 'Tam Dương', 'Vĩnh Tường', 'Yên Lạc'],
    'Yên Bái': ['Yên Bái', 'Nghĩa Lộ', 'Lục Yên', 'Mù Cang Chải', 'Trạm Tấu', 'Trấn Yên', 'Văn Chấn', 'Văn Yên', 'Yên Bình'],
}

export const provinces = [
    'An Giang',
    'Bà Rịa - Vũng Tàu',
    'Bắc Giang',
    'Bắc Kạn',
    'Bạc Liêu',
    'Bắc Ninh',
    'Bến Tre',
    'Bình Định',
    'Bình Dương',
    'Bình Phước',
    'Bình Thuận',
    'Cà Mau',
    'Cần Thơ',
    'Cao Bằng',
    'Đà Nẵng',
    'Đắk Lắk',
    'Đắk Nông',
    'Điện Biên',
    'Đồng Nai',
    'Đồng Tháp',
    'Gia Lai',
    'Hà Giang',
    'Hà Nam',
    'Hà Nội',
    'Hà Tĩnh',
    'Hải Dương',
    'Hải Phòng',
    'Hậu Giang',
    'Hòa Bình',
    'Hưng Yên',
    'Khánh Hòa',
    'Kiên Giang',
    'Kon Tum',
    'Lai Châu',
    'Lâm Đồng',
    'Lạng Sơn',
    'Lào Cai',
    'Long An',
    'Nam Định',
    'Nghệ An',
    'Ninh Bình',
    'Ninh Thuận',
    'Phú Thọ',
    'Phú Yên',
    'Quảng Bình',
    'Quảng Nam',
    'Quảng Ngãi',
    'Quảng Ninh',
    'Quảng Trị',
    'Sóc Trăng',
    'Sơn La',
    'Tây Ninh',
    'Thái Bình',
    'Thái Nguyên',
    'Thanh Hóa',
    'Thừa Thiên Huế',
    'Tiền Giang',
    'Thành phố Hồ Chí Minh',
    'Trà Vinh',
    'Tuyên Quang',
    'Vĩnh Long',
    'Vĩnh Phúc',
    'Yên Bái'
]