const mongoose = require('mongoose');
const Schema = mongoose.Schema
const postSchema = new mongoose.Schema({
    author: { type: Schema.Types.ObjectId, ref: 'User' },
    type: { type: String },
    category: { type: String },
    title : { type : String },
    area: { type: Number},
    num_bedroom: { type: Number },
    num_floor: { type: Number },
    num_bathroom: { type: Number },
    province : { type : String },
    district : { type : String },
    ward : { type : String },
    street : { type : String },
    direction: { type: String },   
    house_no: { type: Number },
    lat : { type : String },
    lon : { type : String },
    project : { type : String },
    price : { type : String },
    unit : { type : String },
    facade : { type : String },
    year_built: { type: Number },
    new: { type: Boolean },
    car_parking: { type: Boolean },
    fully_furnitured: { type: Boolean },
    business_usable: { type: Boolean },
    posted_by_landholder: { type: Boolean },
    description: { type: String },
    contact_name: { type: String } ,
    contact_phone: { type: String },
    contact_email: { type: String },
    listmg : { type : Array, default : [] },
    transaction_status: { type: String, default: 'open' },
    publish_status: { type: String, default: 'pending'},
    createdAt: { type: Date, default: Date.now },
})

module.exports = mongoose.model('Post',postSchema);