const mongoose = require('mongoose');
const Schema = mongoose.Schema
const postSchema = new mongoose.Schema({
    author: { type: Schema.Types.ObjectId, ref: 'User' },
    type: { type: String },
    category: { type: String },
    title : { type : String },
    area: { type: Number},
    num_bedroom: { type: Number },
    num_floor: { type: Number },
    num_bathroom: { type: Number },
    province : { type : String },
    district : { type : String },
    ward : { type : String },
    street : { type : String },
    direction: { type: String },   
    house_no: { type: String },
    lat : { type : String },
    lon : { type : String },
    radius: { type: Number },
    price : { type : String },
    price_unit : { type : String },
    price_in_number: { type : Number },
    facade : { type : Number },
    built_year: { type: Number },
    car_parking: { type: Boolean, default: false },
    fully_furnitured: { type: Boolean, default: false },
    business_usable: { type: Boolean, default: false },
    posted_by_landholder: { type: Boolean, default: false },
    description: { type: String },
    contact_name: { type: String } ,
    contact_phone: { type: String },
    contact_email: { type: String },
    list_img : { type : Array, default : [] },
    transaction_status: { type: String, default: 'open' },
    publish_status: { type: String, default: 'pending'},
    createdAt: { type: Date, default: Date.now },
})

module.exports = mongoose.model('Post',postSchema);